### ISSUE TITLE
[FEATURE] Provide image dimensions in class instance

### ISSUE THREAD

**Issue by jedmao** [heldr/datauri#11]
I could really use the image width and height in the class instance. Setting only the background image is not ideal in CSS and I would love to spit out the image dimensions as well.

**Comment by heldr** [comment]
@jedmao the version 1.0.0-alpha comes with it :smile:

**Comment by heldr** [comment]
See in http://npm.im/datauri

**Comment by jedmao** [comment]
@heldr most excellent! Thanks!
